[package]
name = 'DAT3InvitationNft'
version = '0.0.7'
upgrade_policy = "compatible"
[dependencies]
# # https://github.com/aptos-labs/aptos-core.git
AptosFramework = { local = "../../aptos-core-mainnet/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "../../aptos-core-mainnet/aptos-move/framework/aptos-stdlib" }
AptosToken = { local = "../../aptos-core-mainnet/aptos-move/framework/aptos-token" }
[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
dat3_owner = "0x135138fb03c8b52d9c1c933e35560f2ad523f6e5f152cbe760f77bedfe8f616b"
dat3_nft = "0x13c1aac82e4a11d011aa2780f46332989287b6bfa3d5f78d03a77faaae7bff16"
dat3_nft_reward = "0x81c6f92ad19ceb51c99950afbf7e6d5732ede1de2f51ad533d2a4b49eec85b06"