[package]
name = 'DAT3InvitationNft'
version = '0.0.7'
upgrade_policy = "compatible"
[dependencies]
# # https://github.com/aptos-labs/aptos-core.git
AptosFramework = { local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-token" }


[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
dat3 = "0x3e128ae33009e484f22b27fb5a043b8f056d0a944e6df221dd3f1c0041146cbf"
dat3_admin = "0xb5927b2f0775a04952cbf3ee5d7c3724d6483b1460c2a873ea2d90ca512ded7"
dat3_nft = "0x363fbed1da9a7ab9c662e57219d583c5dac81a84f545296c83f6c3d37a7e70fc"